### ISSUE TITLE
Can't install with fisherman

### ISSUE THREAD

**Issue by BarbzYHOOL** [oh-my-fish/plugin-cd#8] opened 2018-06-11 15:40 UTC
https://github.com/fisherman/fisherman/issues/427

Well I try to get both plugins from fishermand and ohmyfish but there is always a problem, especially with plugin-cd because of the init file

```
source: Error encountered while sourcing file “/root/.config/fish/conf.d/functions/plugin-cd.fish”:
source: No such file or directory
functions: Function “__plugin_cd” does not exist
~/.config/fish/conf.d/cd.init.fish (line 14):
functions -c __plugin_cd cd
^
from sourcing file ~/.config/fish/conf.d/cd.init.fish
        called on line 250 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

```

Would you mind making it fisherman compatible? or when I try to install fisherman plugins on omf, i got this error https://github.com/oh-my-fish/oh-my-fish/issues/614

**Comment by SanCoder-Q** [comment] 2018-06-11 19:44
I will try to identify the issue and try to make it compatible with fisherman if possible.

**Comment by SanCoder-Q** [comment] 2018-06-11 20:27
Just publish a new version. The symlink that fishman create should be fixed.

**Comment by BarbzYHOOL** [comment] 2018-06-12 13:02
This is fixed, thank you very much. I kept switching between omf and fisherman, I'm still not sure which one to use (I prefer omf but fisherman allows me to install all plugins with more ease).

I now have a solution at least ! thank you

**Closed as completed** 2018-06-12 13:02 UTC
Labels: bug

**Comment by OkanEsen** [comment] 2018-10-05 17:13
This issue seems to be appeared again with the new version of Fisherman.

The error I'm getting is exactly the same posted by @BarbzYHOOL.

Issue: https://github.com/jorgebucaran/fisher/issues/450
Release: https://github.com/jorgebucaran/fisher/releases/tag/3.0.0

**Comment by BarbzYHOOL** [comment] 2018-10-06 11:04
Yes but Jorge said he plans to not support oh my fish much, so it seems like it only has started

**Comment by SanCoder-Q** [comment] 2018-10-06 12:10
@OkanEsen It seems I cannot reproduce the issue you have. Could you please provide more details with clear context about how to reproduce the issue? Thank you.

**Comment by OkanEsen** [comment] 2018-10-06 17:52
> @OkanEsen It seems I cannot reproduce the issue you have. Could you please provide more details with clear context about how to reproduce the issue? Thank you.

Oh, sorry, I didn't provide much information, because the error message I get is exactly the same as @BarbzYHOOL. I haven't done much, just install every plugin I had via `fisher add [PLUGIN-NAME]` but to make sure, that the issue doesn't come from installing various plugins together, I removed all plugins and only added yours and the same issue and error persists:

```
source: Error encountered while sourcing file “/home/okan/.config/fish/conf.d/functions/plugin-cd.fish”:
source: No such file or directory
functions: Function “__plugin_cd” does not exist
~/.config/fish/conf.d/plugin-cd_init.fish (line 20):
functions -c __plugin_cd cd
^
from sourcing file ~/.config/fish/conf.d/plugin-cd_init.fish
        called on line 250 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup


       functions -- print or erase functions

   Synopsis
       functions [ -a | --all ] [ -n | --names ]
       functions [ -D | --details ] [ -v ] FUNCTION
       functions -c OLDNAME NEWNAME
       functions -d DESCRIPTION FUNCTION
       functions [ -e | -q ] FUNCTIONS...


functions: Type “help functions” for related documentation

Welcome to fish, the friendly interactive shell
[I] okan@noah ~/.c/fish>
```

The exact procedure:

1. Obviously install Fisher via the method described in the repository.
2. Add this plugin via: `fisher add oh-my-fish/plugin-cd`
3. Restart fish shell.

**Comment by jorgebucaran** [comment] 2018-10-07 05:53
The problem here was nothing to do with Oh My Fish! but plain old bugs. #10 should fix all the errors. 

You can try it in the meantime using:
```
fisher add jorgebucaran/plugin-cd
```
When #10 is merged, please update your ~/.config/fish/fishfile with the correct package URL as I have no use of keeping the fork.

```fish
vim ~/.config/fish/fishfile
```
```diff
- jorgebucaran/plugin-cd
+ oh-my-fish/plugin-cd
```
```
fisher
```

👋 Cheers!

cc @BarbzYHOOL @SanCoder-Q @OkanEsen

**Comment by SanCoder-Q** [comment] 2018-10-07 08:55
@jorgebucaran Thanks for fix it. I will merge the PR.

**Comment by jorgebucaran** [comment] 2018-10-07 08:57
@SanCoder-Q Thanks.
